CREATE TABLE 'event_gacha_data' ('gacha_id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'gacha_name' TEXT NOT NULL, 'item_type' INTEGER NOT NULL, 'item_id' INTEGER NOT NULL, 'cost' INTEGER NOT NULL, 'repeat_step' INTEGER NOT NULL, PRIMARY KEY('gacha_id'));
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10001, /*event_id*/10001, /*gacha_name*/"初音禮物轉蛋", /*item_type*/2, /*item_id*/60002, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10002, /*event_id*/10002, /*gacha_name*/"小小甜心大冒險", /*item_type*/2, /*item_id*/60012, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10004, /*event_id*/10004, /*gacha_name*/"危險的假期！海岸邊的美食公主", /*item_type*/2, /*item_id*/60032, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10005, /*event_id*/10005, /*gacha_name*/"珠希與美冬的無人島０盧幣生活", /*item_type*/2, /*item_id*/60042, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10006, /*event_id*/10006, /*gacha_name*/"黑鐵的亡靈", /*item_type*/2, /*item_id*/60052, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10007, /*event_id*/10007, /*gacha_name*/"不給布丁就搗蛋！約定的萬聖節派對", /*item_type*/2, /*item_id*/60062, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10008, /*event_id*/10008, /*gacha_name*/"暮光破壞者", /*item_type*/2, /*item_id*/60072, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10009, /*event_id*/10009, /*gacha_name*/"忘却的頌歌", /*item_type*/2, /*item_id*/60082, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10010, /*event_id*/10010, /*gacha_name*/"新春破曉之星大危機！", /*item_type*/2, /*item_id*/60092, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10011, /*event_id*/10011, /*gacha_name*/"情人節戰爭！爭鬥心意的甜點對決", /*item_type*/2, /*item_id*/60102, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10012, /*event_id*/10012, /*gacha_name*/"王都的名偵探　嘆息的追緝者", /*item_type*/2, /*item_id*/60112, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10013, /*event_id*/10013, /*gacha_name*/"在阿斯特朗盛開的雙輪之花", /*item_type*/2, /*item_id*/60122, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10014, /*event_id*/10014, /*gacha_name*/"復刻 初音的禮物大作戰", /*item_type*/2, /*item_id*/60132, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10015, /*event_id*/10015, /*gacha_name*/"將軍道中記　白翼的武士", /*item_type*/2, /*item_id*/60142, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10016, /*event_id*/10016, /*gacha_name*/"復刻 小小甜心大冒險", /*item_type*/2, /*item_id*/60152, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/10017, /*event_id*/10017, /*gacha_name*/"Re:從零開始的異世界餐桌", /*item_type*/2, /*item_id*/60162, /*cost*/1, /*repeat_step*/5);
INSERT INTO `event_gacha_data` VALUES (/*gacha_id*/19003, /*event_id*/10003, /*gacha_name*/"吸血鬼獵人 with伊莉亞", /*item_type*/2, /*item_id*/60022, /*cost*/1, /*repeat_step*/5);
