CREATE TABLE 'gift_message' ('id' INTEGER NOT NULL, 'discription' TEXT NOT NULL, 'type_1' INTEGER NOT NULL, 'type_2' INTEGER NOT NULL, 'type_3' INTEGER NOT NULL, 'type_4' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `gift_message` VALUES (/*id*/2001, /*discription*/"「{0}」第{1}天獲得的道具。", /*type_1*/1, /*type_2*/2, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2002, /*discription*/"在「{0}」中所獲得的道具。", /*type_1*/3, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2003, /*discription*/"在「{0}」中所獲得的道具。", /*type_1*/4, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2004, /*discription*/"競技場第{0}名的排名獎勵。", /*type_1*/5, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2005, /*discription*/"公主競技場第{0}名的排名獎勵。", /*type_1*/6, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2006, /*discription*/"{0}月戰隊競賽{1}最終排名第{2}名的獎勵。", /*type_1*/10, /*type_2*/11, /*type_3*/7, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2007, /*discription*/"{0}月戰隊競賽月間排名第{1}名的獎勵。", /*type_1*/10, /*type_2*/8, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2008, /*discription*/"在{0}中所獲得的獎勵。", /*type_1*/9, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2009, /*discription*/"{0}月戰隊競賽排名第{2}名的獎勵。", /*type_1*/10, /*type_2*/11, /*type_3*/7, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3001, /*discription*/"開放公會小屋2樓時所獲得的道具。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3002, /*discription*/"開放公會小屋3樓時所獲得的道具。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9101, /*discription*/"來自營運團隊的誠意獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9102, /*discription*/"來自營運團隊的補償獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9103, /*discription*/"請在挑戰次數為4次以下時領取。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9201, /*discription*/"停機維護的禮物。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9202, /*discription*/"版本更新的禮物。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9203, /*discription*/"來自營運團隊的禮物。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9204, /*discription*/"「事前登錄活動」達成的獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9205, /*discription*/"「事前登錄活動」加碼獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9206, /*discription*/"事前登錄獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9207, /*discription*/"突破50萬次下載的紀念禮物。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9208, /*discription*/"LinksMate 的遊戲連動特典。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9209, /*discription*/"LinksMate 的啟用特典。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9210, /*discription*/"LinksMate 的星星禮物。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9211, /*discription*/"「DMM 版事前登錄活動」的 10 萬人成就獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9301, /*discription*/"超過持有上限後所獲得的體力獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9302, /*discription*/"競技場的防守獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9303, /*discription*/"公主競技場的防守獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9304, /*discription*/"支援戰隊所獲得的獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9305, /*discription*/"戰隊升級前用於強化裝備之道具的一部份。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9306, /*discription*/"轉換主角經驗值後所獲得的瑪那。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9307, /*discription*/"於戰隊競賽的討伐獎勵中所獲得的道具。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9308, /*discription*/"被戰隊成員讚好後所獲得的瑪那。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9309, /*discription*/"超過持有上限後所獲得的競技場時間獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9310, /*discription*/"超過持有上限後所獲得的競技場獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9311, /*discription*/"超過持有上限後所獲得的公主競技場時間獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9312, /*discription*/"超過持有上限後所獲得的公主競技場獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9401, /*discription*/"每日寶石禮包的獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9501, /*discription*/"「活動登入獎勵」中第{1}天所獲得的道具。", /*type_1*/13, /*type_2*/2, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9502, /*discription*/"初次完成活動任務{1}後所獲得的道具。", /*type_1*/13, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9503, /*discription*/"完成活動任務{1}後所獲得的道具。", /*type_1*/13, /*type_2*/14, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9504, /*discription*/"初次擊倒活動Boss「{1}」後所獲得的道具。", /*type_1*/13, /*type_2*/15, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9505, /*discription*/"擊倒活動Boss「{1}」後所獲得的道具。", /*type_1*/13, /*type_2*/15, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9506, /*discription*/"達成活動任務後所獲得的道具。", /*type_1*/13, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9507, /*discription*/"在「{1}」中所獲得的道具。", /*type_1*/13, /*type_2*/12, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99401, /*discription*/"每日瑪那禮包的獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99402, /*discription*/"每日轉蛋禮包的獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99403, /*discription*/"每週轉蛋禮包的獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99404, /*discription*/"每月轉蛋禮包的獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99405, /*discription*/"1回限定禮包的獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99406, /*discription*/"3回限定禮包的獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99407, /*discription*/"購買指定品項獲得獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99408, /*discription*/"儲值指定面額回饋獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99409, /*discription*/"限定碎片禮包獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99410, /*discription*/"電玩雙週刊序號兌換獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99411, /*discription*/"序號兌換獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99412, /*discription*/"7-11限定-貪吃佩可的贈禮", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99413, /*discription*/"7-11限定-可可蘿的贈禮", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99414, /*discription*/"7-11限定-凱留的贈禮", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99415, /*discription*/"2018漫博限定獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99416, /*discription*/"2018漫博限定抽獎獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99417, /*discription*/"《MOMO x 公主連結》MyCard購買獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99418, /*discription*/"《MOMO x 公主連結》MyCard抽獎獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99419, /*discription*/"《MOMO x 公主連結》MyCard滿額獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99420, /*discription*/"特約通路序號兌換獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99421, /*discription*/"So-net 夏日遊戲祭限定獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99422, /*discription*/"2018 漫畫博覽會紀念獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99423, /*discription*/"GooglePlay限定新手禮包", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99424, /*discription*/"掃蕩券量販包", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99425, /*discription*/"MyCard 7-11聯合促銷活動獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99426, /*discription*/"UP直播虛寶獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99427, /*discription*/"獨立碎片禮包獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99428, /*discription*/"精選碎片禮包獎勵。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99429, /*discription*/"經驗藥水量販包", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99430, /*discription*/"公告發布時間問題補償", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99431, /*discription*/"戰隊任務獎勵補償", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99432, /*discription*/"「我的公主我最懂」全服獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99433, /*discription*/"雙平台20萬下載紀念獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99434, /*discription*/"全服冒險通關總星數達1億獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99435, /*discription*/"戰隊滿員且LV15以上獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99436, /*discription*/"達成指定等級獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99437, /*discription*/"擁有★4角色指定數量獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99438, /*discription*/"擁有★5角色指定數量獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99439, /*discription*/"競技場最高紀錄第一名獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99440, /*discription*/"公主競技場最高紀錄第一名獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99441, /*discription*/"競技場勝場數TOP100獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99442, /*discription*/"公主競技場勝場數TOP100獎勵", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
