CREATE TABLE 'hatsune_description' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'description' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `hatsune_description` VALUES (/*id*/1, /*event_id*/10001, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/2, /*event_id*/10001, /*type*/1, /*description*/"進入活動冒險後，頭目將登場。\n使用頭目券，即可挑戰頭目。\n擊敗頭目將獲得大量的討伐證，所以請盡量挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/3, /*event_id*/10001, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/4, /*event_id*/10002, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/5, /*event_id*/10002, /*type*/1, /*description*/"進入活動冒險後，頭目將登場。\n使用頭目券，即可挑戰頭目。\n擊敗頭目將獲得大量的討伐證，所以請盡量挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/6, /*event_id*/10002, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/7, /*event_id*/10003, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/8, /*event_id*/10003, /*type*/1, /*description*/"進入活動冒險後，頭目將登場。\n使用頭目券，即可挑戰頭目。\n擊敗頭目將獲得大量的討伐證，所以請盡量挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/9, /*event_id*/10003, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/10, /*event_id*/10004, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/11, /*event_id*/10004, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/12, /*event_id*/10004, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/13, /*event_id*/10004, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/14, /*event_id*/10005, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/15, /*event_id*/10005, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/16, /*event_id*/10005, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/17, /*event_id*/10005, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/18, /*event_id*/10006, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/19, /*event_id*/10006, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/20, /*event_id*/10006, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/21, /*event_id*/10007, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/22, /*event_id*/10007, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/23, /*event_id*/10007, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/24, /*event_id*/10007, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/25, /*event_id*/10008, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情會將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/26, /*event_id*/10008, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/27, /*event_id*/10008, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802001, /*event_id*/10008, /*type*/2, /*description*/"為尋求工作而前往溪谷洞窟的杏奈。\n為尋找古文書而前往購買處的七七香。\n聽了村人的願望而朝村莊前進的流夏。\n3個人朝向各自的目的地出發了。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802002, /*event_id*/10008, /*type*/2, /*description*/"在村裡爽快懲治了惡棍的流夏。\n與害怕報復的村人談過之後，\n她感到溪谷一帶有著暗中活躍的巨惡。\n另一方面，前往溪谷洞窟的杏奈則是……。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802003, /*event_id*/10008, /*type*/2, /*description*/"杏奈她們雖然在溪谷洞窟開始工作了，\n但該處和先前所說的模樣完全不同，是一處被無法之徒盤據，\n充斥著嚴苛勞動條件的惡劣環境。\n此時，去採買的七七香則是……。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802004, /*event_id*/10008, /*type*/2, /*description*/"因為某個貴族霸佔了古文書，\n七七香無法達成採購的目的。\n她在回程路上遇到惡棍襲擊，\n急忙走上通往與流夏會合的村莊之路……。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802005, /*event_id*/10008, /*type*/2, /*description*/"知道溪谷洞窟就是惡棍的大本營後，\n流夏和七七香決定和杏奈等人會合。\n好不容易救出脫逃的杏奈等人，\n她們一時先從洞窟撤退。");
