CREATE TABLE 'hatsune_unlock_unit_condition' ('id' INTEGER NOT NULL, 'unit_id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'condition_mission_id' INTEGER NOT NULL, 'top_description' TEXT NOT NULL, 'description_1' TEXT NOT NULL, 'description_2' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `hatsune_unlock_unit_condition` VALUES (/*id*/1, /*unit_id*/107601, /*event_id*/10004, /*condition_mission_id*/71004025, /*top_description*/"討伐BOSS解放！\n還有{0}隻", /*description_1*/"[3C404E]進行活動、挑戰BOSS、\n討伐BOSS可解放限定角色！！[-]", /*description_2*/"[3C404E]討伐BOSS（全難易度共通）解放！\n還有[FFBB00,CE4F00]{0}[-]隻[-]");
INSERT INTO `hatsune_unlock_unit_condition` VALUES (/*id*/2, /*unit_id*/108001, /*event_id*/10005, /*condition_mission_id*/71005025, /*top_description*/"討伐BOSS解放！\n還有{0}隻", /*description_1*/"[3C404E]進行活動、挑戰BOSS、\n討伐BOSS可解放限定角色！！[-]", /*description_2*/"[3C404E]討伐BOSS（全難易度共通）解放！\n還有[FFBB00,CE4F00]{0}[-]隻[-]");
INSERT INTO `hatsune_unlock_unit_condition` VALUES (/*id*/3, /*unit_id*/108201, /*event_id*/10007, /*condition_mission_id*/71007031, /*top_description*/"討伐NORMAL BOSS解放！", /*description_1*/"[3C404E]進行活動、挑戰BOSS、\n討伐NORMAL BOSS可解放限定角色！！[-]", /*description_2*/"[3C404E]討伐NORMAL BOSS解放！");
INSERT INTO `hatsune_unlock_unit_condition` VALUES (/*id*/4, /*unit_id*/108501, /*event_id*/10009, /*condition_mission_id*/71009031, /*top_description*/"討伐NORMAL BOSS解放！", /*description_1*/"[3C404E]進行活動、挑戰BOSS、\n討伐NORMAL BOSS可解放限定角色！！[-]", /*description_2*/"[3C404E]討伐NORMAL BOSS解放！");
INSERT INTO `hatsune_unlock_unit_condition` VALUES (/*id*/5, /*unit_id*/108901, /*event_id*/10010, /*condition_mission_id*/71010031, /*top_description*/"討伐NORMAL BOSS解放！", /*description_1*/"[3C404E]進行活動、挑戰BOSS、\n討伐NORMAL BOSS可解放限定角色！！[-]", /*description_2*/"[3C404E]討伐NORMAL BOSS解放！");
INSERT INTO `hatsune_unlock_unit_condition` VALUES (/*id*/6, /*unit_id*/109001, /*event_id*/10011, /*condition_mission_id*/71011031, /*top_description*/"討伐NORMAL BOSS解放！", /*description_1*/"[3C404E]進行活動、挑戰BOSS、\n討伐NORMAL BOSS可解放限定角色！！[-]", /*description_2*/"[3C404E]討伐NORMAL BOSS解放！");
INSERT INTO `hatsune_unlock_unit_condition` VALUES (/*id*/7, /*unit_id*/109301, /*event_id*/10013, /*condition_mission_id*/71013031, /*top_description*/"討伐NORMAL BOSS解放！", /*description_1*/"[3C404E]進行活動、挑戰BOSS、\n討伐NORMAL BOSS可解放限定角色！！[-]", /*description_2*/"[3C404E]討伐NORMAL BOSS解放！");
INSERT INTO `hatsune_unlock_unit_condition` VALUES (/*id*/8, /*unit_id*/109801, /*event_id*/10017, /*condition_mission_id*/71017031, /*top_description*/"討伐NORMAL BOSS解放！", /*description_1*/"[3C404E]進行活動、挑戰BOSS、\n討伐NORMAL BOSS可解放限定角色！！[-]", /*description_2*/"[3C404E]討伐NORMAL BOSS解放！");
