CREATE TABLE 'hatsune_description' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'description' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `hatsune_description` VALUES (/*id*/1, /*event_id*/10001, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/2, /*event_id*/10001, /*type*/1, /*description*/"進入活動冒險後，頭目將登場。\n使用頭目券，即可挑戰頭目。\n擊敗頭目將獲得大量的討伐證，所以請盡量挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/3, /*event_id*/10001, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/4, /*event_id*/10002, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/5, /*event_id*/10002, /*type*/1, /*description*/"進入活動冒險後，頭目將登場。\n使用頭目券，即可挑戰頭目。\n擊敗頭目將獲得大量的討伐證，所以請盡量挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/6, /*event_id*/10002, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/7, /*event_id*/10003, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/8, /*event_id*/10003, /*type*/1, /*description*/"進入活動冒險後，頭目將登場。\n使用頭目券，即可挑戰頭目。\n擊敗頭目將獲得大量的討伐證，所以請盡量挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/9, /*event_id*/10003, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/10, /*event_id*/10004, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/11, /*event_id*/10004, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/12, /*event_id*/10004, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/13, /*event_id*/10004, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/14, /*event_id*/10005, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/15, /*event_id*/10005, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/16, /*event_id*/10005, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/17, /*event_id*/10005, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/18, /*event_id*/10006, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/19, /*event_id*/10006, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/20, /*event_id*/10006, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/21, /*event_id*/10007, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/22, /*event_id*/10007, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/23, /*event_id*/10007, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/24, /*event_id*/10007, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/25, /*event_id*/10008, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情會將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/26, /*event_id*/10008, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/27, /*event_id*/10008, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/28, /*event_id*/10009, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情會將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/29, /*event_id*/10009, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/30, /*event_id*/10009, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/31, /*event_id*/10009, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/32, /*event_id*/10010, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情會將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/33, /*event_id*/10010, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/34, /*event_id*/10010, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/35, /*event_id*/10010, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/36, /*event_id*/10010, /*type*/3, /*description*/"特別戰鬥是有著 3 階段變化的戰鬥模式。\n去取得更豪華的獎勵與任務獎勵吧。由於期間中只能挑戰 1 隻，請多花點心思組成隊伍挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/37, /*event_id*/10011, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/38, /*event_id*/10011, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/39, /*event_id*/10011, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/40, /*event_id*/10011, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/41, /*event_id*/10011, /*type*/3, /*description*/"特別戰鬥是有著 3 階段變化的戰鬥模式。\n去取得更豪華的獎勵與任務獎勵吧。由於期間中只能挑戰 1 隻，請多花點心思組成隊伍挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/42, /*event_id*/10012, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/43, /*event_id*/10012, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/44, /*event_id*/10012, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/45, /*event_id*/10012, /*type*/3, /*description*/"特別戰鬥是有著 3 階段變化的戰鬥模式。\n去取得更豪華的獎勵與任務獎勵吧。由於期間中只能挑戰 1 隻，請多花點心思組成隊伍挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/46, /*event_id*/10013, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/47, /*event_id*/10013, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/48, /*event_id*/10013, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/49, /*event_id*/10013, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/50, /*event_id*/10013, /*type*/3, /*description*/"特別戰鬥是有著 3 階段變化的戰鬥模式。\n去取得更豪華的獎勵與任務獎勵吧。由於期間中只能挑戰 1 隻，請多花點心思組成隊伍挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/51, /*event_id*/10014, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/52, /*event_id*/10014, /*type*/1, /*description*/"進入活動冒險後，頭目將登場。\n使用頭目券，即可挑戰頭目。\n擊敗頭目將獲得大量的討伐證，所以請盡量挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/53, /*event_id*/10014, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/54, /*event_id*/10014, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/55, /*event_id*/10015, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/56, /*event_id*/10015, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/57, /*event_id*/10015, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/58, /*event_id*/10015, /*type*/3, /*description*/"特別戰鬥是有著 3 階段變化的戰鬥模式。\n去取得更豪華的獎勵與任務獎勵吧。由於期間中只能挑戰 1 隻，請多花點心思組成隊伍挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/59, /*event_id*/10016, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/60, /*event_id*/10016, /*type*/1, /*description*/"進入活動冒險後，頭目將登場。\n使用頭目券，即可挑戰頭目。\n擊敗頭目將獲得大量的討伐證，所以請盡量挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/61, /*event_id*/10016, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/62, /*event_id*/10016, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/63, /*event_id*/10017, /*type*/1, /*description*/"可透過活動，體驗特別的劇情。\n活動劇情將於進入活動冒險後解放。");
INSERT INTO `hatsune_description` VALUES (/*id*/64, /*event_id*/10017, /*type*/1, /*description*/"達成活動限定的任務後，可解放的角色\n即會登場。在活動期間內\n以完成任務為目標吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/65, /*event_id*/10017, /*type*/1, /*description*/"強大的VERY HARD Boss登場。\nVERY HARD Boss１天能夠討伐１隻。\n做好萬全準備後，小心地進行挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/66, /*event_id*/10017, /*type*/1, /*description*/"交換討伐證將是得到獎勵的契機。\n獎勵之中，也包含在活動中登場之角色的記憶碎片。\n多多蒐集，將角色變成夥伴吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/67, /*event_id*/10017, /*type*/3, /*description*/"特別戰鬥是有著 3 階段變化的戰鬥模式。\n去取得更豪華的獎勵與任務獎勵吧。\n由於期間中只能挑戰 1 隻，請多花點心思組成隊伍挑戰吧。");
INSERT INTO `hatsune_description` VALUES (/*id*/68, /*event_id*/10017, /*type*/3, /*description*/"在展演模式中，可以重複和SPECIAL的BOSS對戰。n另外，將戰鬥的記錄存檔後就可以回顧戰鬥內容，\n可以用來找尋您專屬的攻略法或嘗試各種編組不同的隊伍對戰。");
INSERT INTO `hatsune_description` VALUES (/*id*/69, /*event_id*/10017, /*type*/4, /*description*/"挑戰活動任務和BOSS時，有時候會出現信賴度故事。　　　　　　　　信賴度將會按照對話的內容提升，　　　　　　　　達到特定的信賴度時可獲得禮物。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802001, /*event_id*/10008, /*type*/2, /*description*/"為尋求工作而前往溪谷洞窟的杏奈。\n為尋找古文書而前往購買處的七七香。\n聽了村人的願望而朝村莊前進的流夏。\n3個人朝向各自的目的地出發了。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802002, /*event_id*/10008, /*type*/2, /*description*/"在村裡爽快懲治了惡棍的流夏。\n與害怕報復的村人談過之後，\n她感到溪谷一帶有著暗中活躍的巨惡。\n另一方面，前往溪谷洞窟的杏奈則是……。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802003, /*event_id*/10008, /*type*/2, /*description*/"杏奈她們雖然在溪谷洞窟開始工作了，\n但該處和先前所說的模樣完全不同，是一處被無法之徒盤據，\n充斥著嚴苛勞動條件的惡劣環境。\n此時，去採買的七七香則是……。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802004, /*event_id*/10008, /*type*/2, /*description*/"因為某個貴族霸佔了古文書，\n七七香無法達成採購的目的。\n她在回程路上遇到惡棍襲擊，\n急忙走上通往與流夏會合的村莊之路……。");
INSERT INTO `hatsune_description` VALUES (/*id*/1000802005, /*event_id*/10008, /*type*/2, /*description*/"知道溪谷洞窟就是惡棍的大本營後，\n流夏和七七香決定和杏奈等人會合。\n好不容易救出脫逃的杏奈等人，\n她們一時先從洞窟撤退。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001002001, /*event_id*/10010, /*type*/2, /*description*/"獻上心願與進行淨化的神殿。\n由於未能達成的「實體化的願望」會襲擊人們，\n所以與優衣她們一起接受委託來此擔任警衛。\n為了要將報酬拿來當做紅包而參加了警衛的工作。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001002002, /*event_id*/10010, /*type*/2, /*description*/"就算參拜的人在匆忙之中，也是一面幫著其他\n有困難的人，每個人都負責了自己的工作。\n此時遇上了要尋找親人的「實體化的願望」，\n最後與日和她們溫柔地扮演了父母完成了淨化。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001002003, /*event_id*/10010, /*type*/2, /*description*/"雖然大家都習慣了工作，此時卻出現了一個\n想知道如何和女朋友接吻的「實體化的願望」。\n但是，看到了主角抱住倒下的優衣時的樣子，\n就在嘴唇快要親到的前一刻，完成了淨化。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001002004, /*event_id*/10010, /*type*/2, /*description*/"時間越晚，參拜的人變得越多，也跟著忙了起來。\n此時「實體化的願望」出現了。\n那個想要獲得鼓勵而振作的嘆息與徬徨，\n就靠著怜「拼命」的聲援而完成了淨化。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001002005, /*event_id*/10010, /*type*/2, /*description*/"將許多的願望淨化完成後，大家準備想休息時，\n來到了願望最為濃烈的年末前幾小時，\n此時願望一個接著一個的實體化了。\n這些失控的願望化成了一團黑霧籠罩著神殿。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001702001, /*event_id*/10017, /*type*/2, /*description*/"【美食殿堂】一行人遭到一位名叫貝特魯吉烏斯的男人襲擊。\n在千鈞一髮之際將身為魔女教大罪司教的他擊退，\n與【美食殿堂】交情漸深的愛蜜莉雅一行人\n就這樣在【咲戀育幼院】住了下來。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001702002, /*event_id*/10017, /*type*/2, /*description*/"王宮騎士團因大罪司教貝特魯吉烏斯暗地裡的動作頻繁，而有所動作，\n派遣副團長克莉絲提娜前往某個村落。\n愛蜜莉雅一行人從凱留那裡得知大罪司教的動向\n他們一邊戒備著他神秘的能力，一邊前往現場。");
INSERT INTO `hatsune_description` VALUES (/*id*/1001702003, /*event_id*/10017, /*type*/2, /*description*/"一行人趕到陷入苦戰的克莉絲提娜的身邊。\n原本看似有利的情勢，卻因魔女教徒的出現瞬間逆轉。\n有愛蜜莉雅一行人加入的【美食殿堂】利用魔法的冰塊\n孤立貝特魯吉烏斯，向他發出最終的挑戰！");
CREATE INDEX 'hatsune_description_0_event_id_1_type' on 'hatsune_description'('event_id','type');
