CREATE TABLE 'unit_background' ('unit_id' INTEGER NOT NULL, 'unit_name' TEXT NOT NULL, 'bg_id' INTEGER NOT NULL, 'bg_name' TEXT NOT NULL, 'position' REAL NOT NULL, 'face_type' INTEGER NOT NULL, PRIMARY KEY('unit_id'));
INSERT INTO `unit_background` VALUES (/*unit_id*/100101, /*unit_name*/"春咲 日和", /*bg_id*/500040, /*bg_name*/"蘭德索爾 公會小屋", /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/100201, /*unit_name*/"草野 優衣", /*bg_id*/500040, /*bg_name*/"蘭德索爾 公會小屋", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100301, /*unit_name*/"士條 怜", /*bg_id*/500040, /*bg_name*/"蘭德索爾 公會小屋", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/100401, /*unit_name*/"穗高 禊", /*bg_id*/500140, /*bg_name*/"普拉諾平原", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100501, /*unit_name*/"織原 茉莉", /*bg_id*/500090, /*bg_name*/"蘭德索爾 王城入口", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100601, /*unit_name*/"風宮 茜里", /*bg_id*/500260, /*bg_name*/"古城", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100701, /*unit_name*/"出雲 宮子", /*bg_id*/500260, /*bg_name*/"古城", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100801, /*unit_name*/"虹村 雪", /*bg_id*/500140, /*bg_name*/"普拉諾平原", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/100901, /*unit_name*/"柊 杏奈", /*bg_id*/500050, /*bg_name*/"蘭德索爾 餐廳內", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/101001, /*unit_name*/"姫宮 真步", /*bg_id*/500060, /*bg_name*/"哞哞自衛隊 據點", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101101, /*unit_name*/"衣之咲 璃乃", /*bg_id*/500030, /*bg_name*/"蘭德索爾 繁華街", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101201, /*unit_name*/"柏崎 初音", /*bg_id*/500180, /*bg_name*/"精靈之森", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/101301, /*unit_name*/"丹野 七七香", /*bg_id*/500050, /*bg_name*/"蘭德索爾 餐廳內", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/101401, /*unit_name*/"霧原霞", /*bg_id*/500060, /*bg_name*/"哞哞自衛隊 據點", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101501, /*unit_name*/"愛川 美里", /*bg_id*/500180, /*bg_name*/"精靈之森", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101601, /*unit_name*/"美波 鈴奈", /*bg_id*/500080, /*bg_name*/"月光學院", /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/101701, /*unit_name*/"喜屋武 香織", /*bg_id*/500060, /*bg_name*/"哞哞自衛隊 據點", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/101801, /*unit_name*/"支倉 伊緒", /*bg_id*/500080, /*bg_name*/"月光學院", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102001, /*unit_name*/"茜 美美", /*bg_id*/500140, /*bg_name*/"普拉諾平原", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/102101, /*unit_name*/"栗林 胡桃", /*bg_id*/500110, /*bg_name*/"咲戀育幼院 大廳", /*position*/0.0, /*face_type*/5);
INSERT INTO `unit_background` VALUES (/*unit_id*/102201, /*unit_name*/"風宮 依里", /*bg_id*/500260, /*bg_name*/"古城", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102301, /*unit_name*/"北條 綾音", /*bg_id*/500110, /*bg_name*/"咲戀育幼院 大廳", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102501, /*unit_name*/"天野 鈴莓", /*bg_id*/500110, /*bg_name*/"咲戀育幼院 大廳", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102601, /*unit_name*/"森近 鈴", /*bg_id*/500150, /*bg_name*/"伊麗莎白牧場 據點", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/102701, /*unit_name*/"倉石 惠理子", /*bg_id*/500050, /*bg_name*/"蘭德索爾 餐廳內", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102801, /*unit_name*/"佐佐木 咲戀", /*bg_id*/500110, /*bg_name*/"咲戀育幼院 大廳", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/102901, /*unit_name*/"櫻井 望", /*bg_id*/500010, /*bg_name*/"蘭德索爾 市中心", /*position*/0.0, /*face_type*/1);
INSERT INTO `unit_background` VALUES (/*unit_id*/103001, /*unit_name*/"妮諾‧珠貝爾", /*bg_id*/500140, /*bg_name*/"普拉諾平原", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103101, /*unit_name*/"上喜 忍", /*bg_id*/500260, /*bg_name*/"古城", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103201, /*unit_name*/"藤堂 秋乃", /*bg_id*/500070, /*bg_name*/"墨丘利財團 據點", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103301, /*unit_name*/"野戶 真陽", /*bg_id*/500150, /*bg_name*/"伊麗莎白牧場 據點", /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/103401, /*unit_name*/"綾瀬 優花梨", /*bg_id*/500070, /*bg_name*/"墨丘利財團 據點", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/103601, /*unit_name*/"冰川 鏡華", /*bg_id*/500140, /*bg_name*/"普拉諾平原", /*position*/0.0, /*face_type*/1);
INSERT INTO `unit_background` VALUES (/*unit_id*/103701, /*unit_name*/"御久間 智", /*bg_id*/500090, /*bg_name*/"蘭德索爾 王城入口", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/103801, /*unit_name*/"柏崎 栞", /*bg_id*/500150, /*bg_name*/"伊麗莎白牧場 據點", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104001, /*unit_name*/"雙葉 碧", /*bg_id*/500180, /*bg_name*/"精靈之森", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104201, /*unit_name*/"三角 千歌", /*bg_id*/500010, /*bg_name*/"蘭德索爾 市中心", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/104301, /*unit_name*/"安藝 真琴", /*bg_id*/500060, /*bg_name*/"哞哞自衛隊 據點", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104401, /*unit_name*/"伊莉亞‧奧恩斯坦", /*bg_id*/500260, /*bg_name*/"古城", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/104501, /*unit_name*/"遠見 空花", /*bg_id*/500140, /*bg_name*/"普拉諾平原", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/104601, /*unit_name*/"宮坂 珠希", /*bg_id*/500070, /*bg_name*/"墨丘利財團 據點", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/104701, /*unit_name*/"白銀 純", /*bg_id*/500090, /*bg_name*/"蘭德索爾 王城入口", /*position*/0.0, /*face_type*/1);
INSERT INTO `unit_background` VALUES (/*unit_id*/104801, /*unit_name*/"大神 美冬", /*bg_id*/500070, /*bg_name*/"墨丘利財團 據點", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/104901, /*unit_name*/"星野 静流", /*bg_id*/500030, /*bg_name*/"蘭德索爾 繁華街", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/105001, /*unit_name*/"玉泉 美咲", /*bg_id*/500080, /*bg_name*/"月光學院", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/105101, /*unit_name*/"宵濱 深月", /*bg_id*/500050, /*bg_name*/"蘭德索爾 餐廳內", /*position*/0.0, /*face_type*/6);
INSERT INTO `unit_background` VALUES (/*unit_id*/105201, /*unit_name*/"莉瑪", /*bg_id*/500150, /*bg_name*/"伊麗莎白牧場 據點", /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/105301, /*unit_name*/"莫妮卡‧拜斯溫特", /*bg_id*/500140, /*bg_name*/"普拉諾平原", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/105401, /*unit_name*/"繭宮 紡希", /*bg_id*/500010, /*bg_name*/"蘭德索爾 市中心", /*position*/0.0, /*face_type*/9);
INSERT INTO `unit_background` VALUES (/*unit_id*/105501, /*unit_name*/"石橋 步未", /*bg_id*/500140, /*bg_name*/"普拉諾平原", /*position*/0.0, /*face_type*/15);
INSERT INTO `unit_background` VALUES (/*unit_id*/105601, /*unit_name*/"太刀洗 流夏", /*bg_id*/500050, /*bg_name*/"蘭德索爾 餐廳內", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/105701, /*unit_name*/"吉塔", /*bg_id*/500200, /*bg_name*/"布里薩溪谷", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/105801, /*unit_name*/"貪吃佩可", /*bg_id*/500130, /*bg_name*/"埃斯特雷拉街道", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/105901, /*unit_name*/"可可蘿", /*bg_id*/500130, /*bg_name*/"埃斯特雷拉街道", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/106001, /*unit_name*/"凱留", /*bg_id*/500130, /*bg_name*/"埃斯特雷拉街道", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/106101, /*unit_name*/"矛依未", /*bg_id*/500341, /*bg_name*/"拉比林斯的公會據點", /*position*/0.0, /*face_type*/20);
INSERT INTO `unit_background` VALUES (/*unit_id*/106301, /*unit_name*/"亞里莎", /*bg_id*/500170, /*bg_name*/"神秘森林", /*position*/0.0, /*face_type*/3);
INSERT INTO `unit_background` VALUES (/*unit_id*/106801, /*unit_name*/"模索路晶", /*bg_id*/500030, /*bg_name*/"蘭德索爾 繁華街", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/107101, /*unit_name*/"克莉絲提娜‧摩根", /*bg_id*/500090, /*bg_name*/"蘭德索爾 王城入口", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/107501, /*unit_name*/"貪吃佩可（夏日）", /*bg_id*/500164, /*bg_name*/"瑪爾傑海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/107601, /*unit_name*/"可可蘿（夏日）", /*bg_id*/500164, /*bg_name*/"瑪爾傑海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/107701, /*unit_name*/"鈴莓（夏日）", /*bg_id*/500164, /*bg_name*/"瑪爾傑海岸", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/107801, /*unit_name*/"凱留（夏日）", /*bg_id*/500164, /*bg_name*/"瑪爾傑海岸", /*position*/0.0, /*face_type*/6);
INSERT INTO `unit_background` VALUES (/*unit_id*/107901, /*unit_name*/"珠希（夏日）", /*bg_id*/500284, /*bg_name*/"無人島", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108001, /*unit_name*/"美冬（夏日）", /*bg_id*/500284, /*bg_name*/"無人島", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108101, /*unit_name*/"忍（萬聖節）", /*bg_id*/500264, /*bg_name*/"古城 萬聖節", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108201, /*unit_name*/"宮子（萬聖節）", /*bg_id*/500264, /*bg_name*/"古城 萬聖節", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108301, /*unit_name*/"美咲（萬聖節）", /*bg_id*/505030, /*bg_name*/"蘭德索爾 繁華街 萬聖節", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108401, /*unit_name*/"千歌（聖誕節）", /*bg_id*/500114, /*bg_name*/"咲戀育幼院 大廳 聖誕節", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/108501, /*unit_name*/"胡桃（聖誕節）", /*bg_id*/500114, /*bg_name*/"咲戀育幼院 大廳 聖誕節", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108601, /*unit_name*/"綾音（聖誕節）", /*bg_id*/500114, /*bg_name*/"咲戀育幼院 大廳 聖誕節", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108701, /*unit_name*/"日和（新年）", /*bg_id*/500553, /*bg_name*/"新年 神殿", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108801, /*unit_name*/"優衣（新年）", /*bg_id*/500553, /*bg_name*/"新年 神殿", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/108901, /*unit_name*/"怜（新年）", /*bg_id*/500553, /*bg_name*/"新年 神殿", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/109001, /*unit_name*/"惠理子（情人節）", /*bg_id*/500600, /*bg_name*/"廚房競技場", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109101, /*unit_name*/"靜流（情人節）", /*bg_id*/500600, /*bg_name*/"廚房競技場", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109201, /*unit_name*/"安", /*bg_id*/500133, /*bg_name*/"埃斯特雷拉街道", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/109301, /*unit_name*/"露", /*bg_id*/500133, /*bg_name*/"埃斯特雷拉街道", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109401, /*unit_name*/"古蕾婭", /*bg_id*/500133, /*bg_name*/"埃斯特雷拉街道", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109501, /*unit_name*/"空花（大江戶）", /*bg_id*/500650, /*bg_name*/"大江戶大街", /*position*/0.0, /*face_type*/4);
INSERT INTO `unit_background` VALUES (/*unit_id*/109601, /*unit_name*/"妮諾（大江戶）", /*bg_id*/500650, /*bg_name*/"大江戶大街", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/109701, /*unit_name*/"雷姆", /*bg_id*/500175, /*bg_name*/"神秘森林", /*position*/0.0, /*face_type*/2);
INSERT INTO `unit_background` VALUES (/*unit_id*/109801, /*unit_name*/"拉姆", /*bg_id*/500175, /*bg_name*/"神秘森林", /*position*/0.0, /*face_type*/12);
INSERT INTO `unit_background` VALUES (/*unit_id*/109901, /*unit_name*/"愛蜜莉雅", /*bg_id*/500175, /*bg_name*/"神秘森林", /*position*/0.0, /*face_type*/2);
